### ISSUE TITLE
KaTeX math failing to render

### ISSUE THREAD

**Issue by UtkarshVerma** [gpoore/codebraid-preview-vscode#1]
The math equations aren't being rendered out of the box for me, while they work with another Markdown preview. Here's a recording:

https://user-images.githubusercontent.com/31820255/156712109-fa83f9cf-07e8-474f-8efd-546d5068e4fe.mp4

**Comment by gpoore** [comment]
I just released a new version that should fix this. There were some issues with packaging KaTeX as part of the extension.

**Comment by UtkarshVerma** [comment]
Thanks for the quick fix. It works. Thank you for working on the previewer as well. I can't express how much I've wanted something like this for VS Code as I extensively use `pandoc` for making my reports.
