### ISSUE TITLE
Numbering and cross-references 

### ISSUE THREAD

**Issue by i-thot-u-wanted2dance** [gpoore/codebraid-preview-vscode#11]
Is it the case that with the `commonmark_x` format one cannot use the [two most widely used filters for cross-referencing](https://pandoc.org/extras.html#numbering-and-cross-references) (i.e., `pandoc-crossref` and `pandoc-xnos`)?

**Comment by gpoore** [comment]
There isn't a lot of documentation about `commonmark_x` details. The best source I have found is https://github.com/jgm/pandoc/wiki/Roadmap. If those filters rely on citations, then they wouldn't work...citations seem to be perhaps the biggest feature currently missing from all CommonMark-based formats.
