### ISSUE TITLE
Add previewing images support

### ISSUE THREAD

**Issue by mateibarbu19** [gpoore/codebraid-preview-vscode#13]
Hello, I couldn't get images to load using your extension.

After searching the [Webview Content Security Policy instructions](https://code.visualstudio.com/api/extension-guides/webview#content-security-policy), I found that adding the `img-src ${webview.cspSource} https:;` snippet to this [line](https://github.com/gpoore/codebraid-preview-vscode/blob/a0b86ada92919492a77e69589781131bca59103b/src/preview_panel.ts#L214) works well.

Is this a feature you wish to add? Or is there a security risk I missed?

Thanks.

**Comment by gpoore** [comment]
Just to clarify, are you working with local or remote images? Local images work for me, but if you are having issues with local images you may be using a different directory structure or something else may be interfering.

The content security policy does need options for customization.

**Comment by mateibarbu19** [comment]
I'm working with both type of images. I don't have a problem with local ones, but would like to preview documents in which URIs to remote images are used. Thanks.

**Comment by gpoore** [comment]
I've just released v0.11.0, which includes a new setting `codebraid.preview.security.allowRemoteImages`. If you turn this on, it adds `https:` to the content security policy and enables remote images.  The new release also includes many other settings for customizing the content security policy.

**Comment by mateibarbu19** [comment]
Thanks! It will help me as I want to use pandoc to generate presentations from Markdown.
