### ISSUE TITLE
[custom html template compatibility] Everything almost worked, but Codebraid did not say which HTML code is invalid

### ISSUE THREAD

**Issue by gusbemacbe** [gpoore/codebraid-preview-vscode#20]
Hello!

I am always facing a same problem:

![image](https://github.com/gpoore/codebraid-preview-vscode/assets/2257024/8c9a9a75-d199-40f9-b417-98788e66ad1b)

I reviewed the default and template files, and the Codebraid settings, and did not find any error in these files. I do not know why. 

I use the latest version of Pandoc, and of Codebraid. 

You can get my tiny and simple file to analyse: [small-bugged-test.tar.gz](https://github.com/gpoore/codebraid-preview-vscode/files/13798048/small-bugged-test.tar.gz). 

I also tried this command, but it was stuck:

```sh
pandoc --defaults "confluence.yaml" --template "assets/templates/confluence.html" --file-scope --standalone --from markdown_github --to html -o "result.html"
```

**Comment by gpoore** [comment]
Your `log-file` entry in `confluence.yaml` is causing issues. I'd suggest debugging on the command line. You need to add `README.md` to the end of your command so that it has input (otherwise Pandoc just waits for input from STDIN).

**Comment by gusbemacbe** [comment]
1. I commented the `log-file`, but Codebraid still complains the invalid HTML.
2. I adjusted again the command, and it worked with or without `log-file`. 

I don't understand why it does not work on Codebraid Preview.

**Comment by gpoore** [comment]
After disabling `log-file`, the remaining issue is the custom template `confluence.html`. Try replacing the current `charset` with `<meta charset="UTF-8" />` (note ` /` at end). Everything is currently designed for the default Pandoc template output, and I need to modify this to deal with custom templates.

**Comment by gusbemacbe** [comment]
It worked. But after I updated the Pandoc template, it stopped worked. Here is the updated template with difference highlighting:

```diff
+ $if(confluence_html)$
<html $if(lang)$lang="$lang$"$endif$>
    <head>
        <meta charset="UTF-8" />
        <meta name="generator" content="pandoc">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>$if(title-prefix)$$title-prefix$ - $endif$$pagetitle$</title>
    </head>
    <body>
+$endif$
    <div class="ids-markdown">
        Testing...
        $body$
    </div>
+$if(confluence_html)$
    </body>
</html>
+$endif$
```

And here's a small default file code about `variables`:

```yml
variables:
  confluence_html: false
```

If I changed it to `true`, it worked fully.

**Comment by gusbemacbe** [comment]
Observe that, after the suggestion about the `charset` you gave me, I enabled the `log-file`, and it worked on Codebraid Preview. Just disabling the `html` and `body` elements with the `confluence_html` key with the value `false` for the `variables` will not work.

**Comment by gpoore** [comment]
Just changing `charset` should be enough. I don't know why you're adding a `confluence_html` variable in your template. You want a complete HTML document for the preview.

**Comment by gusbemacbe** [comment]
Because Atlassian Confluence has a HTML editor plugin. In the HTML editor plugin, it doesn't use the `html` and `body` elements, except `link` and `script` elements. 

If I use the elements `html` and `body` on the Confluence page article, the HTML will not be displayed in the preview. 

I keep that variable to `true` only to test the final version. Once it looks good, I change to `false`, and I'll print it to HTML and copy it to the Confluence page article.

**Comment by gusbemacbe** [comment]
@gpoore 

Your extension can't deal with the `css`, `include-before-body` and `include-after-body`.

**Comment by gusbemacbe** [comment]
The old versions of Codebraid Preview could deal with these parts. 

I have to use the full command until these bugs be fixed.

**Comment by gpoore** [comment]
Can you provide more detail? `css`, `include-before-body`, and `include-after-body` seem to be working fine for me. Where and how are you specifying these? What full command are you using?

**Comment by gusbemacbe** [comment]
- `css`: Codebraid informed that it was an invalid HTML.
- `include-before-body` and `include-after-body`: it almost worked, but the CSS files did not appear in the HTML document.

You can check at the Pandoc documentation and receive my compressed file to test and analyse. 

- Pandoc documentation about `css`: https://pandoc.org/MANUAL.html#options-affecting-specific-writers-1
- Compressed file: [confluence.tar.gz](https://github.com/gpoore/codebraid-preview-vscode/files/13810813/confluence.tar.gz)

Here is the full command:

```sh
pandoc README.md --preserve-tabs --standalone --wrap="auto" --defaults "confluence.yaml" --from markdown_github+auto_identifiers+bracketed_spans+fenced_code_attributes+fenced_divs+inline_code_attributes+markdown_in_html_blocks+raw_attribute+raw_html+simple_tables-smart+startnum --to html -o "README.html"
```

**Comment by gpoore** [comment]
In your template `confluence.html`, try putting `<meta charset="UTF-8" />` on the line immediately after `<head>`. This follows the order of the default Pandoc template, which is what Codebraid Preview expects. I need to make the requirements for custom templates more flexible when possible, and also document the requirements based on the default Pandoc template.

**Comment by gpoore** [comment]
I've made the preview more robust for working with custom Pandoc HTML templates. It no longer depends on the exact format or location of `meta charset`. A new release will be out in the next few days, or you can try the current development version: [codebraid-preview-0.16.0-dev2.vsix.zip](https://github.com/gpoore/codebraid-preview-vscode/files/13850890/codebraid-preview-0.16.0-dev2.vsix.zip).

You will need to make a few changes to your template to work with the new version:
* Add `<!doctype html>` at the beginning of the template.
* Add CSS so that Codebraid Preview messages and general formatting display properly. Within `<head>`, add this:
  ```
  $for(css)$
  <link rel="stylesheet" href="$css$" />
  $endfor$
  ```
  You can model this off the default Pandoc template, which can be viewed by running `pandoc --print-default-template=html`.
* You can continue using your `confluence_html` variable. I've added a new `codebraid_preview` template variable that can be used as an alternative. So you can use a conditional like this in the preview to detect whether the HTML is being used within the preview or elsewhere:
  ```
  $if(codebraid_preview)$
  ...
  $else$
  ...
  $endif$
  ```

**Comment by gusbemacbe** [comment]
It worked fully. But I am unable to export with Pandoc. When I click `Pandoc` at the bottom menubar, the pop-up window does not show up. I use the KDE desktop environment.

**Comment by gpoore** [comment]
I'd suggest restarting VS Code and when you try to export, checking for error messages in the panel under the output tab, Codebraid Preview dropdown. It's working for me. No code related to export has been changed recently.

**Comment by gusbemacbe** [comment]
I migrated from Endeavour OS to MX Linux, and was able to open the pop-up window when I exported with Pandoc. It is remarkable that `codebraid_preview` suppresses some elements. It was what I wanted exactly. But I would like to skip all `span` elements and `data-pos` attributes when to export, is it possible?

**Comment by gpoore** [comment]
The settings/code that create `data-pos` attributes for scroll sync are only used in generating the preview HTML. Whenever you export with Pandoc, none of that is used. The `data-pos` attributes are created with `+sourcepos` for `commonmark_x` and other CommonMark-based formats, and with Lua filters otherwise, so that is just omitted in exporting.
