### ISSUE TITLE
[Feature Request] Add refresh button to preview (Allow me to refresh the preview if I modify other non-Markdown files)

### ISSUE THREAD

**Issue by gusbemacbe** [gpoore/codebraid-preview-vscode#24]
Good evening!

When I modify or change some files, like CSS, HTML, or JavaScript files every time, I have to click the Markdown file, close the Codebraid preview and open it every time.

I know I can click «|> Codebraid», but it will fail and give the following error: 

> Could not find codebraid executable. Code execution is disabled. Install from https://pypi.org/project/codebraid/, 0.10.3+.

Observe that I have already installed Codebraid via `poetry self add codebraid` and exported the `$HOME/.local/share/pypoetry/venv/bin` to `$PATH`. 

I would refresh the Codebraid preview without having to go to the Markdown, close and open the Codebraid Paid.

**Comment by gpoore** [comment]
I don't think there's a good way to automatically detect all files that are involved in the preview. There are so many ways that CSS and JavaScript can be included.

Currently, the preview only refreshes when a Markdown document, or the `_codebraid_preview.yaml`, is modified. Would an option to automatically refresh the preview every few seconds (which you could adjust in settings) do what you want?

**Comment by gusbemacbe** [comment]
Your plugin does not need to detect all files involved in the preview. Only a refresh icon, like Microsoft's [Live Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server). The Live Preview has a refresh icon:

![image](https://github.com/gpoore/codebraid-preview-vscode/assets/2257024/07e3a261-bf95-4df4-98fa-dec16e877dac)

I just click «Codebraid Refresh» on the preview menubar, next to «▷ Codebraid» or just to click «▷ Codebraid» to refresh.

**Comment by gpoore** [comment]
I'll look into adding a refresh button.

**Comment by gpoore** [comment]
I've just released a new version that includes a refresh button.

**Comment by gusbemacbe** [comment]
Hello @gpoore 

I updated the extension, but I did not find the refresh button:

![image](https://github.com/gpoore/codebraid-preview-vscode/assets/2257024/547d7c69-f831-44d3-bd85-e8b6da1aae0a)

**Comment by gpoore** [comment]
It isn't in the toolbar across the bottom, but in the top-right hand of the preview window. Over time, I may move some of the other buttons to the same location, to keep the bottom toolbar less cluttered.

**Comment by gusbemacbe** [comment]
Hello @gpoore!

I apologise for my long absence. I have been very busy with my job.

I understood what happened and why I did not find the refresh button. It turned out that I set `codebraid.preview.css.useDefault` to `false`, and I had to change to `true`. To override Codebraid Preview's CSS default, I had to set `codebraid.preview.css.overrideDefault` to `true`. It worked perfectly. 

Thank you a lot.

**Comment by gusbemacbe** [comment]
Good morning, @gpoore! 

I'm at the work now. I discovered that the refresh button disappeared because some of CSS elements put the body over the refresh button, even if your Codebraid toolbar is already set to 100 for `z-index`. When I tested several times to click the preview, I could catch a glimpse of the refresh button before it disappeared. Observe that I have already set `true` to `codebraid.preview.css.useDefault`, but the refresh button still disappeared. 

However, I can't share the CSS files because of my company's privacy and security policies. But I can tell you it's similar to Normalize and Bootstrap's CSS reboot or reset codes.

**Comment by gusbemacbe** [comment]
If it can't be solved, I think that the solution is that you can add the refresh command to the Command Palette with or without a shortcut, what will be totally easy if the developers have trouble finding the refresh button because of their CSS codes.

**Comment by gpoore** [comment]
I will separate the CSS for the refresh toolbar from the other CSS, so that it won't depend on `codebraid.preview.css.useDefault`, and include the toolbar CSS after user CSS so that it is more difficult to modify accidentally. If that doesn't fix things, then I'll look into ways of adding a refresh button elsewhere. Either way, I'll add a refresh command to the Command Palette, since that is guaranteed to be available and work.
