### ISSUE TITLE
how to add pandoc arguments

### ISSUE THREAD

**Issue by dswbx** [gpoore/codebraid-preview-vscode#3]
From the readme, it says one should add pandoc arguments as follows:

```
codebraid.preview.pandoc.options [none]: Pandoc command-line options in array form (for example, ["--filter", "FILTER"]).
```

I've tried several ways but it won't take my options, tried it in different ways (`settings.json`):
```
{
  "codebraid.preview.pandoc.options": [
      "`[\"--filter\", \"pandoc-crossref\"]`",
      "[\"--filter\", \"pandoc-crossref\"]",
      "[--filter, pandoc-crossref]",
      "\"--filter=pandoc-crossref\"",
      "--filter=pandoc-crossref",
   ],
}
```

But none of them seems to work. Could you assist how to add them correctly?

**Comment by gpoore** [comment]
This should be fixed in the new release. As part of fixing this and some related issues, I changed argument handling, so an entire option including any value is now in a single string.
```
{
  ...
  "codebraid.preview.pandoc.options": [
      "--filter pandoc-crossref"
   ],
  ...
}
```
