### ISSUE TITLE
Please publish to [open-vsx.org](https://open-vsx.org/) in addition to the VS Code Marketplace

### ISSUE THREAD

**Issue by mfhepp** [gpoore/codebraid-preview-vscode#7]
[VSCodium](https://github.com/VSCodium/vscodium) is the open-source build of VSCode, with less/no telemetry sent to MS etc.

Would it be possible to publish this great extension also on the [open-vsx.org](https://open-vsx.org/) marketplace in addition to the VS Code Marketplace?

The publishing process is documented in the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Thanks!

**Comment by gpoore** [comment]
It's published: https://open-vsx.org/extension/gpoore/codebraid-preview.

Let me know if there are any issues.
