### ISSUE TITLE
You overwrote our syntax highlighting CSS

### ISSUE THREAD

**Issue by gusbemacbe** [gpoore/codebraid-preview-vscode#8]
Hello,

We have own syntax highlighting CSS. We use Prism.js or Highlight.js.

Using VSCode's native Markdown Preview, our syntax highlighting CSS is used and not overwritten.

But with your extension, our syntax highlighting isn't used and is overwritten.

**Comment by gpoore** [comment]
The preview is generated with Pandoc and uses Pandoc's default syntax highlighting. If you want to customize that, you'll need to pass additional options to the pandoc executable or perhaps add a filter in the defaults file. To get started with that, you may want to look at https://github.com/jgm/pandoc/issues/3858 (especially the end) and https://github.com/pandoc/lua-filters/tree/master/revealjs-codeblock. There may be other relevant issues related to customizing syntax highlighting in the Pandoc repo.

**Comment by gusbemacbe** [comment]
Did you mean to add a filter to `_codebraid_preview.yaml` file?

```yaml
title: Teste
filters:
   - revealjs-codeblock.lua
```

**Comment by gpoore** [comment]
Yes, if you find a filter that will do what you need, adding it to `_codebraid_preview.yaml` is probably the easiest option at the moment. It's also possible to change the Pandoc options globally by modifying `codebraid.preview.pandoc.options` in the VS Code settings.

**Comment by gusbemacbe** [comment]
I do not know if your `_codebraid_preview.yaml` supports `template` option. But I tried to test, including this option and with `filter: revealjs-codeblock.lua`, but the code remains the same. 

I tried @averms' `standard-code.lua`, but it gave an error: `standard-code.lua:6: syntax error near 'local'`

@kiwi0fruit's `language_prefix.py` almost worked, but the code wasn't rendered.

**Comment by gpoore** [comment]
`_codebraid_preview.yaml` currently only supports `filters`, `input-files`, and `from`. You could add something of the form `--template=FILE` to `codebraid.preview.pandoc.options` in the VS Code settings to see if that will work. It looks like you might also need `-V highlightjs`, based on the example at https://github.com/pandoc/lua-filters/tree/master/revealjs-codeblock.

**Comment by gusbemacbe** [comment]
I tried, but unfortunately the code isn't rendered and didn't change the colours.

**Comment by gpoore** [comment]
I think I figured out why it isn't working. It's trying to load remote JavaScript, and the preview webview has content security policies in place that prevent that. I may be able to add a setting that disables the security policies, or bundle more JavaScript libraries as part of the extension, but that probably isn't something I can get to in the near future.

**Comment by gusbemacbe** [comment]
> the preview webview has content security policies in place that prevent that

You can base your project on Micosoft's @mjbvz's [extensions/markdown-language-features](https://github.com/microsoft/vscode/tree/543748094188ac02d23ee406c91d68012599d182/extensions/markdown-language-features).

**Comment by gpoore** [comment]
I've just released v0.11.0, which includes new settings under `codebraid.preview.security` for customizing the content security policy. By turning on settings like `codebraid.preview.security.allowInlineScripts`, `codebraid.preview.security.allowLocalScripts` `codebraid.preview.security.allowRemoteScripts`, and `codebraid.preview.security.allowRemoteStyles`, it should now be possible to get any combination of local and remote JavaScript and CSS working. If you are using local resources outside the document directory/workspace, you may also need to modify `codebraid.preview.security.extraLocalResourceRoots` to give the preview access to the location of those resources.
